name: Pacman Contribution Graph

on:
  schedule:
    - cron: "0 * * * *" # runs every hour to keep the graph updated
  workflow_dispatch: # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman SVG
        uses: maurodesouza/pacman-contribution-graph@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Options:
          # color: "#00FF00"      # (optional) change pacman color
          # background: "dark"    # "dark" or "light"
